### ISSUE TITLE
JLD2 Issue on Windows Substem for Linux

### ISSUE THREAD

**Issue by AliGhorashiCMT** [thchr/Crystalline.jl#17]

**Comment by AliGhorashiCMT** [comment]
I'm using the computer I had at MIT. I'm getting this error when trying to add crystalline to it: 

Unsatisfiable requirements  detected for package JLD2 
JLD2 has no known versions

**Comment by thchr** [comment]
Try to do `pkg> up`? If that fails, try to remove the entire package directory and Project.toml and file and start over (as we did last time). It works fine on WSL for me.

**Comment by AliGhorashiCMT** [comment]
I think I have some general problem with WSL using julia- I'll use my Mac for now

**Comment by thchr** [comment]
Okay, I'll close this in the interim then; feel free to reopen if you can reproduce it "cleanly" :)
