### ISSUE TITLE
SquareStaticMatrices.jl as its own package?

### ISSUE THREAD

**Issue by brainandforce** [thchr/Crystalline.jl#53]
I find this functionality sufficiently useful that I think it warrants being spun off into its own package. It's nice to not have an extra type parameter dangling in various struct definitions.

**Comment by thchr** [comment]
Hmm, yeah, that makes sense. I don't have the cycles to do it this week - but maybe one of the coming weeks. Right now, it just implements the minimum functionality that I needed - I guess it would need a bit more polish to be generally used.

**Comment by brainandforce** [comment]
I've created my own very simple implementation here: https://github.com/brainandforce/LengthFreeStaticMatrices.jl

This one handles non-square matrices, so it should hopefully be more flexible. I haven't implemented any of the bits that use generated functions, though, so performance could be better.
